version: '3.9'

services: 
  db:
    platform: linux/x86_64 
    image: mariadb:latest
    container_name: Q3_Database
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Q3_PhpMyAdmin
    links:
      - db
    environment:
      PMA_HOST: db
    ports:
      - 8080:80