version: '3.9'

services: 
  db:
    image: mysql:latest
    container_name: Authentication_Database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'q3_auth'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: Authentication_PhpMyAdmin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80
